// Flutter icons Wellkins
// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.
//
// To use this font, place it in your fonts/ directory and include the
// following in your pubspec.yaml
//
// flutter:
//   fonts:
//    - family:  Wellkins
//      fonts:
//       - asset: fonts/Wellkins.ttf
//
//
// * Entypo, Copyright (C) 2012 by Daniel Bruce
//         Author:    Daniel Bruce
//         License:   SIL (http://scripts.sil.org/OFL)
//         Homepage:  http://www.entypo.com
// * Material Design Icons, Copyright (C) Google, Inc
//         Author:    Google
//         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
//         Homepage:  https://design.google.com/icons/
// * Linecons, Copyright (C) 2013 by Designmodo
//         Author:    Designmodo for Smashing Magazine
//         License:   CC BY ()
//         Homepage:  http://designmodo.com/linecons-free/
// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
//         Author:    Aristeides Stathopoulos
//         License:   SIL (http://scripts.sil.org/OFL)
//         Homepage:  http://aristeides.com/
// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
//         Author:    Dave Gandy
//         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
//         Homepage:  http://fortawesome.github.com/Font-Awesome/
//
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class Wellkins {
  Wellkins._();

  static const _kFontFam = 'Wellkins';
  static const String? _kFontPkg = null;

  static const IconData settings =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voting =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuffle =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noti =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
